### ISSUE TITLE
请问prefetch_path是用来做什么的？

### ISSUE THREAD

**Issue by Lqh3034** [SJTU-Quant/LIFT#2]
Loading prefetch files from D:/pythonProject5/LIFT-main/prefetch/ETTh1_L336_max_train.npz
Fail to load prefetch files
Traceback (most recent call last):
  File "D:\pythonProject5\LIFT-main\data_provider\data_loader.py", line 541, in _load_prefetch_files
    assert prefetch_path and os.path.exists(prefetch_path)
AssertionError
Traceback (most recent call last):
  File "D:\pythonProject5\LIFT-main\data_provider\data_loader.py", line 541, in _load_prefetch_files
    assert prefetch_path and os.path.exists(prefetch_path)
AssertionError
在 D:/pythonProject5/LIFT-main/prefetch/这个路径里面，prefetch是一个空的文件夹，它的里面并没有ETTh1_L336_max_train.npz，请问我该如何修改代码

**Comment by MogicianXD** [comment]
No need to revise the code. The AssertionError is meant to inform you that we have not precomputed lead-lag relationships yet. The program will automatically generate files under the 'prefetch_path'. Then error messages will not reappear the next time.
